src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $nb_personne = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $disponibilite = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    #[ORM\JoinColumn(name: "id_utilisateur", referencedColumnName: "id", nullable: false)]

    private ?Utilisateur $id_utilisateur = null;

    /**
     * @var Collection<int, Reservation>
     */
    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'id_annonce')]
    private Collection $reservations;

    /**
     * @var Collection<int, Avis>
     */
    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'id_annonce')]
    private Collection $avis;

    /**
     * @var Collection<int, Image>
     */
    #[ORM\OneToMany(targetEntity: Image::class, mappedBy: 'id_annonce')]
    private Collection $images;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNbPersonne(): ?int
    {
        return $this->nb_personne;
    }

    public function setNbPersonne(int $nb_personne): static
    {
        $this->nb_personne = $nb_personne;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDisponibilite(): ?\DateTimeInterface
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(\DateTimeInterface $disponibilite): static
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $id_utilisateur): static
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setIdAnnonce($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getIdAnnonce() === $this) {
                $reservation->setIdAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setIdAnnonce($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getIdAnnonce() === $this) {
                $avi->setIdAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setIdAnnonce($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getIdAnnonce() === $this) {
                $image->setIdAnnonce(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(name: "id_annonce", referencedColumnName: "id", nullable: false)]
    private ?Annonce $id_annonce = null;


    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(name: "id_utilisateur", referencedColumnName: "id", nullable: false)]
    private ?Utilisateur $id_utilisateur = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getIdAnnonce(): ?Annonce
    {
        return $this->id_annonce;
    }

    public function setIdAnnonce(?Annonce $id_annonce): static
    {
        $this->id_annonce = $id_annonce;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $id_utilisateur): static
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\Annonce;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ReservationController extends AbstractController
{
    #[Route('/mes-reservation/list', name: 'reservation_list')]
    public function list(EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        
        // Si l'utilisateur est un propriétaire, on affiche les réservations de ses annonces
        if ($this->isGranted('ROLE_PROPRIETAIRE')) {
            $annonces = $em->getRepository(Annonce::class)->findBy(['id_utilisateur' => $user]);
            $reservations = [];
            foreach ($annonces as $annonce) {
                $reservations = array_merge($reservations, $annonce->getReservations()->toArray());
            }
        } else {
            // Sinon on affiche les réservations de l'utilisateur
            $reservations = $em->getRepository(Reservation::class)->findBy(['id_utilisateur' => $user]);
        }
        
        return $this->render('reservation/list.html.twig', [
            'reservations' => $reservations,
            'user' => $user
        ]);
    }

    #[Route('/mes-reservation/{id}', name: 'reservation_read')]
    public function read(EntityManagerInterface $em, int $id): Response
    {
        $reservation = $em->getRepository(Reservation::class)->find($id);
        if (!$reservation) {
            throw $this->createNotFoundException("La réservation n'existe pas.");
        }
        
        // Vérification que l'utilisateur a le droit de voir cette réservation
        $user = $this->getUser();
        if ($user !== $reservation->getIdUtilisateur() && 
            $user !== $reservation->getIdAnnonce()->getIdUtilisateur()) {
            throw $this->createAccessDeniedException("Vous n'avez pas accès à cette réservation.");
        }
        
        return $this->render('reservation/read.html.twig', [
            'reservation' => $reservation
        ]);
    }

    #[Route('/mes-reservation/delete/{id}', name: 'reservation_delete')]
    public function delete(EntityManagerInterface $em, int $id): Response
    {
        $reservation = $em->getRepository(Reservation::class)->find($id);
        if (!$reservation) {
            throw $this->createNotFoundException("La réservation n'existe pas.");
        }
        
        // Vérification que l'utilisateur a le droit de supprimer cette réservation
        $user = $this->getUser();
        if ($user !== $reservation->getIdUtilisateur() && 
            $user !== $reservation->getIdAnnonce()->getIdUtilisateur()) {
            throw $this->createAccessDeniedException("Vous n'avez pas la permission de supprimer cette réservation.");
        }
        
        $em->remove($reservation);
        $em->flush();
        
        $this->addFlash('success', 'Réservation supprimée avec succès !');
        return $this->redirectToRoute('reservation_list');
    }
}

templates/reservation/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Réservations - ChezToiChezMoi{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>
        /* Style général */
        .reservations-page {
            padding: 6rem 2rem 4rem;
            max-width: 1200px;
            margin: 0 auto;
            min-height: 100vh;
            background-color: #f8f5f1;
        }
        
        /* Titre */
        .reservations-header {
            text-align: center;
            margin-bottom: 3rem;
        }
        
        .reservations-header h1 {
            color: #333;
            font-size: 2.5rem;
            margin-bottom: 1rem;
            font-weight: 600;
            position: relative;
            display: inline-block;
        }
        
        .reservations-header h1:after {
            content: '';
            position: absolute;
            bottom: -10px;
            left: 50%;
            transform: translateX(-50%);
            width: 80px;
            height: 3px;
            background: #beac75;
        }
        
        .reservations-header i {
            color: #beac75;
            margin-right: 12px;
        }
        
        /* Liste des réservations */
        .reservation-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(380px, 1fr));
            gap: 2rem;
        }
        
        /* Carte de réservation */
        .reservation-card {
            background: white;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(0,0,0,0.05);
            transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
            border: 1px solid rgba(190, 172, 117, 0.2);
        }
        
        .reservation-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 15px 35px rgba(0,0,0,0.1);
            border-color: rgba(190, 172, 117, 0.4);
        }
        
        .reservation-image {
            height: 180px;
            width: 100%;
            object-fit: cover;
            border-bottom: 1px solid rgba(190, 172, 117, 0.1);
        }
        
        .reservation-content {
            padding: 1.8rem;
        }
        
        .reservation-title {
            color: #333;
            font-size: 1.4rem;
            margin-bottom: 1.2rem;
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .reservation-title i {
            color: #beac75;
        }
        
        .reservation-detail {
            display: flex;
            align-items: flex-start;
            gap: 12px;
            margin-bottom: 1rem;
            color: #555;
            line-height: 1.5;
        }
        
        .reservation-detail i {
            color: #beac75;
            margin-top: 2px;
            flex-shrink: 0;
        }
        
        /* Boutons */
        .reservation-actions {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
            padding-top: 1.5rem;
            border-top: 1px solid rgba(190, 172, 117, 0.1);
        }
        
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 0.8rem 1.5rem;
            border-radius: 8px;
            font-weight: 500;
            text-decoration: none;
            transition: all 0.3s ease;
            flex: 1;
            text-align: center;
            font-size: 0.95rem;
        }
        
        .btn-primary {
            background: #beac75;
            color: white;
            border: none;
        }
        
        .btn-primary:hover {
            background: #a89b6d;
            transform: translateY(-2px);
        }
        
        .btn-outline {
            background: transparent;
            color: #beac75;
            border: 1px solid #beac75;
        }
        
        .btn-outline:hover {
            background: rgba(190, 172, 117, 0.1);
        }
        
        /* Message vide */
        .no-reservations {
            text-align: center;
            padding: 4rem 2rem;
            color: #666;
            max-width: 600px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.05);
        }
        
        .no-reservations i {
            font-size: 3rem;
            color: #beac75;
            margin-bottom: 1.5rem;
        }
        
        .no-reservations p {
            font-size: 1.1rem;
            margin-bottom: 2rem;
        }
        
        /* Badge statut */
        .reservation-status {
            display: inline-block;
            padding: 0.3rem 0.8rem;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 500;
            margin-left: auto;
            background: rgba(190, 172, 117, 0.1);
            color: #8B5E3B;
        }
        
        /* Responsive */
        @media (max-width: 768px) {
            .reservation-list {
                grid-template-columns: 1fr;
            }
            
            .reservations-header h1 {
                font-size: 2rem;
            }
        }
    </style>
{% endblock %}

{% block body %}
    <div class="reservations-page">
        <div class="reservations-header">
            <h1><i class="fas fa-calendar-alt"></i> Mes Réservations</h1>
        </div>

        {% if reservations|length > 0 %}
            <div class="reservation-list">
                {% for reservation in reservations %}
                    {# Calcul de la durée du séjour #}
                    {% set arrivalDate = reservation.dateDebut|date('Y-m-d') %}
                    {% set departureDate = reservation.dateFin|date('Y-m-d') %}
                    {% set difference = date(departureDate).diff(date(arrivalDate)) %}
                    {% set nights = difference.days %}

                    <div class="reservation-card">
                        {% if reservation.idAnnonce.images|length > 0 %}
                            <img src="{{ asset('uploads/images/' ~ reservation.idAnnonce.images|first.chemin) }}" 
                                 alt="{{ reservation.idAnnonce.titre }}" 
                                 class="reservation-image">
                        {% else %}
                            <img src="{{ asset('images/default_room.jpg') }}" 
                                 alt="Chambre par défaut" 
                                 class="reservation-image">
                        {% endif %}
                        
                        <div class="reservation-content">
                            <h3 class="reservation-title">
                                <i class="fas fa-home"></i>
                                {{ reservation.idAnnonce.titre }}
                                <span class="reservation-status">Confirmée</span>
                            </h3>
                            
                            <div class="reservation-detail">
                                <i class="fas fa-calendar-day"></i>
                                <span>
                                    <strong>Arrivée :</strong> {{ reservation.dateDebut|date('d/m/Y') }}<br>
                                    <strong>Départ :</strong> {{ reservation.dateFin|date('d/m/Y') }}<br>
                                    <strong>Durée :</strong> {{ nights }} nuit{% if nights > 1 %}s{% endif %}
                                </span>
                            </div>
                            
                            <div class="reservation-detail">
                                <i class="fas fa-map-marker-alt"></i>
                                <span>{{ reservation.idAnnonce.adresse }}, {{ reservation.idAnnonce.ville }}</span>
                            </div>
                            
                            <div class="reservation-actions">
                                <a href="{{ path('reservation_read', {'id': reservation.id}) }}" class="btn btn-primary">
                                    <i class="fas fa-info-circle"></i> Détails
                                </a>
                                <a href="{{ path('reservation_delete', {'id': reservation.id}) }}" 
                                   class="btn btn-outline" 
                                   onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette réservation ?');">
                                    <i class="fas fa-trash-alt"></i> Supprimer
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="no-reservations">
                <i class="fas fa-calendar-times"></i>
                <p>Vous n'avez aucune réservation pour le moment.</p>
                <a href="{{ path('app_chambres') }}" class="btn btn-primary">
                    <i class="fas fa-search"></i> Explorer nos chambres
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/reservation/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma réservation - {{ reservation.idAnnonce.titre }} - ChezToiChezMoi{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        /* Style général */
        .reservation-detail-page {
            padding: 5rem 2rem;
            max-width: 1000px;
            margin: 0 auto;
            background-color: #f8f5f1;
            min-height: 100vh;
        }
        
        /* Conteneur principal */
        .reservation-container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.05);
            overflow: hidden;
            border: 1px solid rgba(190, 172, 117, 0.2);
        }
        
        /* En-tête */
        .reservation-header {
            padding: 2rem;
            background: linear-gradient(135deg, #f9f7f4 0%, #e8e1d3 100%);
            border-bottom: 1px solid rgba(190, 172, 117, 0.2);
            text-align: center;
        }
        
        .reservation-header h1 {
            color: #333;
            font-size: 1.8rem;
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 12px;
            flex-wrap: wrap;
        }
        
        .reservation-header i {
            color: #beac75;
        }
        
        .reservation-status {
            display: inline-block;
            padding: 0.4rem 1rem;
            border-radius: 20px;
            font-size: 0.9rem;
            font-weight: 500;
            background: rgba(190, 172, 117, 0.2);
            color: #8B5E3B;
        }
        
        /* Contenu */
        .reservation-content {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 0;
        }
        
        /* Colonne image */
        .reservation-image-container {
            padding: 2rem;
            border-right: 1px solid rgba(190, 172, 117, 0.1);
        }
        
        .reservation-image {
            width: 100%;
            height: 300px;
            object-fit: cover;
            border-radius: 8px;
        }
        
        /* Colonne info */
        .reservation-info {
            padding: 2rem;
        }
        
        /* Sections d'information */
        .info-section {
            margin-bottom: 2rem;
        }
        
        .info-section h2 {
            color: #333;
            font-size: 1.3rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid rgba(190, 172, 117, 0.2);
            display: flex;
            align-items: center;
            gap: 8px;
        }
        
        .info-section h2 i {
            color: #beac75;
            font-size: 1.1rem;
        }
        
        .info-item {
            display: flex;
            gap: 12px;
            margin-bottom: 1rem;
            color: #555;
        }
        
        .info-item i {
            color: #beac75;
            margin-top: 3px;
            flex-shrink: 0;
        }
        
        .info-item strong {
            color: #333;
            font-weight: 500;
        }
        
        /* Boutons */
        .action-buttons {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
            padding-top: 2rem;
            border-top: 1px solid rgba(190, 172, 117, 0.2);
        }
        
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 0.8rem 1.5rem;
            border-radius: 8px;
            font-weight: 500;
            text-decoration: none;
            transition: all 0.3s ease;
            flex: 1;
        }
        
        .btn-primary {
            background: #beac75;
            color: white;
            border: none;
        }
        
        .btn-primary:hover {
            background: #a89b6d;
            transform: translateY(-2px);
        }
        
        .btn-outline {
            background: transparent;
            color: #beac75;
            border: 1px solid #beac75;
        }
        
        .btn-outline:hover {
            background: rgba(190, 172, 117, 0.1);
        }
        
        /* Responsive */
        @media (max-width: 768px) {
            .reservation-content {
                grid-template-columns: 1fr;
            }
            
            .reservation-image-container {
                border-right: none;
                border-bottom: 1px solid rgba(190, 172, 117, 0.1);
            }
            
            .reservation-header h1 {
                font-size: 1.5rem;
            }
        }
    </style>
{% endblock %}

{% block body %}
    <div class="reservation-detail-page">
        <div class="reservation-container">
            <div class="reservation-header">
                <h1>
                    <i class="fas fa-calendar-check"></i>
                    Ma réservation : {{ reservation.idAnnonce.titre }}
                    <span class="reservation-status">Confirmée</span>
                </h1>
            </div>
            
            <div class="reservation-content">
                <div class="reservation-image-container">
                    {% if reservation.idAnnonce.images|length > 0 %}
                        <img src="{{ asset('uploads/images/' ~ reservation.idAnnonce.images|first.chemin) }}" 
                             alt="{{ reservation.idAnnonce.titre }}" 
                             class="reservation-image">
                    {% else %}
                        <img src="{{ asset('images/default_room.jpg') }}" 
                             alt="Chambre par défaut" 
                             class="reservation-image">
                    {% endif %}
                </div>
                
                <div class="reservation-info">
                    {# Calcul de la durée du séjour #}
                    {% set arrivalDate = reservation.dateDebut|date('Y-m-d') %}
                    {% set departureDate = reservation.dateFin|date('Y-m-d') %}
                    {% set difference = date(departureDate).diff(date(arrivalDate)) %}
                    {% set nights = difference.days %}
                    
                    <div class="info-section">
                        <h2><i class="fas fa-info-circle"></i> Détails de l'annonce</h2>
                        <div class="info-item">
                            <i class="fas fa-align-left"></i>
                            <div>
                                <strong>Description :</strong> {{ reservation.idAnnonce.description }}
                            </div>
                        </div>
                        <div class="info-item">
                            <i class="fas fa-map-marker-alt"></i>
                            <div>
                                <strong>Adresse :</strong> {{ reservation.idAnnonce.adresse }}, {{ reservation.idAnnonce.ville }}
                            </div>
                        </div>
                        <div class="info-item">
                            <i class="fas fa-euro-sign"></i>
                            <div>
                                <strong>Prix :</strong> {{ reservation.idAnnonce.prix }} € / nuit
                            </div>
                        </div>
                    </div>
                    
                    <div class="info-section">
                        <h2><i class="fas fa-calendar-alt"></i> Mon séjour</h2>
                        <div class="info-item">
                            <i class="fas fa-calendar-day"></i>
                            <div>
                                <strong>Arrivée :</strong> {{ reservation.dateDebut|date('d/m/Y à H:i') }}
                            </div>
                        </div>
                        <div class="info-item">
                            <i class="fas fa-calendar-times"></i>
                            <div>
                                <strong>Départ :</strong> {{ reservation.dateFin|date('d/m/Y à H:i') }}
                            </div>
                        </div>
                        <div class="info-item">
                            <i class="fas fa-moon"></i>
                            <div>
                                <strong>Durée :</strong> {{ nights }} nuit{% if nights > 1 %}s{% endif %}
                            </div>
                        </div>
                    </div>
                    
                    <div class="action-buttons">
                        <a href="{{ path('reservation_list') }}" class="btn btn-primary">
                            <i class="fas fa-arrow-left"></i> Retour
                        </a>
                        
                        <a href="{{ path('reservation_delete', {'id': reservation.id}) }}" 
                           class="btn btn-outline" 
                           onclick="return confirm('Êtes-vous sûr de vouloir annuler cette réservation ?');">
                            <i class="fas fa-times"></i> Annuler
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}